### ISSUE TITLE
problem gulp

### ISSUE THREAD

**Issue by ghost** [jdrda/olapus#1]
bower_components/iCheck/iCheck.js <-- Not Found
resources/assets/css/admin/AdminLTE.css <-- Not Found
resources/assets/css/admin/skins/_all-skins.css <-- Not Found
resources/assets/js/admin/squarethis.js <-- Not Found
resources/assets/js/admin/iCheck.js <-- Not Found
resources/assets/js/admin/app.js <-- Not Found

**Comment by jdrda** [comment]
Please check the new version of /gulpfile.js I have commited, if it works for you.

**Comment by ghost** [comment]
Yes it works.
I changed the name of:
with Adminlte on adminlte in gulpfile.js
Thank you!

**Comment by jdrda** [comment]
Great, I released new version with this and other small corrections, so it can be updated with GIT. Closing ticket.
